# ----------------------------------------------------------------------------
#
# config
#
# ----------------------------------------------------------------------------

sudo: false
language: node_js

# we only care about the theme branch
branches:
  only:
    - theme

# notify srcc#github
notifications:
  slack:
    secure: P6lX6ZJ6s6CMtbcG1jCTZYqVf7QJfYcaZdmtXqd3mm16Iiiaw4/DyqE/knSSEcG0wbVopZI/0UM48UHPSmmTJ6wkKKVlsj7A8qWzn6zT/euMu8c4TDNOCplOcgVj8IRJN+L1K+j9lbxz/c2yEUUjd4BdZwpy8g0fum+oKqZE7P/1AgikkvddccW0nMxN801ZwF0AQw35KgdToWYhPFEyjjOlWfYlW9w2SmwTDnnZSStexCBgrJ3Iq9EorRH4BL1zaeieiDQQHWkXhSaK6MR4QPu7nPVH3AHpGHh5m+3dDRbi4/NT26gHWwgC+CsKUtnyFl44H2vpoVX+CMO0RsVH9tEDwparn5dqytXpC2LqpgD4JYPpdJ5wMQt9FCO9NQKaK/Bqf5H1y7D3O+jqgLrKXzLk5xc6WXAamHSTJlz4V5cEk+JL5vd2lUYyPWrtZZiBagMCWSlN66zIFdSxHdQbjJ303VaJ82XFMPtLgYdJN8OJwb4dfFvpjbZUmW+54thB8Nh7Ghvf4602KbdMsbtdI0QXtQP+nNkLdePyrd6RiWokffWSLxqwzOgI+qEQm8QFeFGUswYn6e5cMwUnpfCyyfexaeO7sOGeRhxNWJmvO3dT3e7NLct0fu1hnzWFExwqhSg6EwQFjMh+jPTDxUWXhf20fDFFIzwr6Jpc29EDvxY=


# ----------------------------------------------------------------------------
#
# build
#
# ----------------------------------------------------------------------------

# Node.js version
node_js: 8

# limit clone depth to 5, to speed up build
git:
  depth: 5

# cache dependencies
cache:
  pip: true
  directories:
  - node_modules

# install yarn before anything else
before_install:
  - |
    # check that we actually need to build anything
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
    fi
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(\.git|\.editor|doc|material|site|scripts|CHANGELOG|LICENSE))/' || {
      echo "Only non-source files were updated, no need to trigger a build."
      exit
    }
  - npm install -g yarn@v0.22.0

# install dependencies
install:
  - npm install
  - pip install --user -r requirements.txt

# build
script:
  - npm run lint
  - npm run build


# ----------------------------------------------------------------------------
#
# deployment
#
# ----------------------------------------------------------------------------

# deploy
#   fetch docs and copy contents of material/ there, then commit and push
after_success:
  - |
    # git config (global since we'll change repos to commit)
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name  "Travis CI"
    git config --global push.default simple
    # fetch docs
    git clone https://${DEPLOY_KEY}@github.com/stanford-rc/www.sherlock.stanford.edu.git --branch docs --single-branch /tmp/docs/
    # copy output there
    rsync -avP --delete material/ /tmp/docs/theme/
    # commit+push changes
    cd /tmp/docs/
    git add -A theme/
    git commit -m "Travis deploy from $TRAVIS_BRANCH to $(git rev-parse --abbrev-ref HEAD): ${TRAVIS_COMMIT:0:7}

    Travis build: $TRAVIS_BUILD_NUMBER"
    git push

