# ----------------------------------------------------------------------------
#
# config
#
# ----------------------------------------------------------------------------

language: python
sudo: false

# we only care about the theme branch
branches:
  only:
    - theme

# notify srcc#github
notifications:
  slack:
    secure: jCnui9VydF+7LKuRWwe6YqKaBgSmjksJaI4ec2LASIgdg6k2FyRreYdse5SnC10cATAuJzMu5J7oQC0QZi6lllUfFQ8BNDoL9hSnPEWzKPMnLKJrMASMx7AxkDqDWhjgVcRDO7nG9tAEonPDSpPouVV3fqelD0HO4Sn/E2KSOUgkUXqIS2lpKnVo0j7kEXV0PybTjtSI0Qy3Xw3DEUTEzywhAFy01OUpkY5pifpX+dX46TnPnsuBs62nvlTfShTGw566UtQ+wH7R80jkYog0iQ5n7bmSBbIWdAMLmMAamcxNS6Rby+qbn19QWFn0SvlAbI6T7RqJTpeREYioRS/KYzqg9xI2CkniXiLxGBERrg55GGnBK/7z68vi5tfzBxUSXbKHNCgOfOAMwsUUOpFqIl0g0a8cGbMVlrq4vz9zHLIYWeI39l6EcEr+b3ONxW6xMw73MQz0Sx64G3OM4uLeToGCmhv2BqwIYfAoghhv1JYmeSFtNlKRGpN9dFWPQFZLN1LIwHe1Qbzv5xf8IsHBPpTuDuChuaACqevMrBdrEqT8exQMT4t1z//EiTd4nWWxrZhULdDZxYARun4uUuAExcNV2aLQMGv1krbkokpTWbw+1jSDeDroBNLrGcNLeBaDIUfgCdr242HgTtMwxWJNLyXi1n6t7OHaRSorNw8n9+g=


# ----------------------------------------------------------------------------
#
# build
#
# ----------------------------------------------------------------------------

# Python, Node.js version and necessary services
python: "3.6"
node_js: "8"

# limit clone depth to 5, to speed up build
git:
  depth: 5

# cache dependencies
cache:
  pip: true
  directories:
  - node_modules

# install yarn before anything else
before_install:
  - |
    # check that we actually need to build anything
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
    fi
    git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(\.git|\.editor|doc|material|site|scripts|CHANGELOG|LICENSE))/' || {
      echo "Only non-source files were updated, no need to trigger a build."
      exit
    }
#  - npm install -g yarn@v0.22.0

# install dependencies
install:
  - npm install
  - pip install -r requirements.txt

# build
script:
  - npm run lint
  - npm run build


# ----------------------------------------------------------------------------
#
# deployment
#
# ----------------------------------------------------------------------------

# deploy
#   fetch docs and copy contents of material/ there, then commit and push
after_success:
  - |
    # git config (global since we'll change repos to commit)
    git config --global user.email "travis@travis-ci.org"
    git config --global user.name  "Travis CI"
    git config --global push.default simple
    # fetch docs
    git clone https://${DEPLOY_KEY}@github.com/stanford-rc/www.sherlock.stanford.edu.git --branch docs --single-branch /tmp/docs/
    # copy output there
    rsync -avP --delete material/ /tmp/docs/theme/
    # commit+push changes
    cd /tmp/docs/
    git add -A theme/
    git commit -m "Travis deploy from $TRAVIS_BRANCH to $(git rev-parse --abbrev-ref HEAD): ${TRAVIS_COMMIT:0:7}

    Travis build: $TRAVIS_BUILD_NUMBER"
    git push

