sudo: false
language: node_js

# we only care about the web_theme branch
branches:
    only:
        - web_theme

# Node.js version
node_js: 5

# limit clone depth to 5, to speed up build
git:
    depth: 5

# cache dependencies
cache:
    pip: true
    yarn: true
    directories:
        - node_modules

# install yarn before anything else
before_install:
    - npm install -g yarn@v0.22.0

# install dependencies
install:
    - yarn install --ignore-optional
    - pip install --user -r requirements.txt

# build
script: 
    - yarn build

# deploy
after_success:
    - script: ./sh_deploy.sh

