sudo: false
language: node_js

# we only care about the web_theme branch
branches:
    only:
        - web_theme

# Node.js version
node_js: 5

# limit clone depth to 5, to speed up build
git:
    depth: 5

# cache dependencies
cache:
    pip: true
    yarn: true
    directories:
        - node_modules

# install yarn before anything else
before_install:
    - npm install -g yarn@v0.22.0

# install dependencies
install:
    - yarn install --ignore-optional
    - pip install --user -r requirements.txt

# build
script: 
    - yarn build

# deploy
#   fetch web_docs and copy contents of material/ there, then commit and push
after_success:
    - |
     git config user.email "travis@travis-ci.com"
     git config user.name  "Travis CI"
     git config --global push.default simple
     git add material/
     git stash
     git remote add -t web_docs origin2 https://${DEPLOY_KEY}@github.com/stanford-rc/sherlock.git
     git fetch origin2
     git checkout web_docs
     git checkout web_theme material/
     git add -A material/
     git commit -m "Travis deploy from $TRAVIS_BRANCH to $(git rev-parse --abbrev-ref HEAD): ${TRAVIS_COMMIT:0:7}
      
     Travis build: $TRAVIS_BUILD_NUMBER"
     git push
