# ----------------------------------------------------------------------------
#
# config
#
# ---------------------------------------------------------------------------- 

sudo: false
language: node_js

# we only care about the web_theme branch
branches:
    only:
        - web_theme

# notify srcc#github
notifications:
    slack:
        secure: "5LH3JMgre8bvoyVXvZs/TF5oWUiAAUTiRrLJ9g+2D63QlXtDt82PCf/wnzx16xiIaNk26IzmEs5McvDSoAH2eaHxOBa20zlHqxnZiy0nqQTP1QT6yxVMBXt95FaEbvptqmsD60PovacY563o5Cmp0JfhdHuJAy/kE+oNkgzYbiuliLTx1qJAidIvKaEaglVMQG9UzKk+5mtW33K/a2EKMI8I45whmloEnBjHjkhAqBA93nn6l6f+HAfLSsVGjxL4p95Nvi/Te9q/4VTmPleZLQoXDTKF9/IaASu1wBEZPkF1R5/sdtYxsp9UZv/G63aPwBQ7ZvpzuRDU/Hs40R3LFUW2mbYgTPloUpOygnVRxFIpiVYFDQs/HvcILN2d21+9yCn0Kb2Xbqk1l43hh9I0VkSSRnJx6whPZ3yBepbJusQq0nQGe+VET8sL38zsCBc2d3DnEK1vYgwohe3tMEpu/BXFcL7+rHHQAj/+XOwsDZdRO+uGfL+Eb52286tsSxlA3BcM7TX2BGwdSAQOX+fJQ9QHRcN0oB3KUcXCydgEJwi7uVuU6LTcvdvb1oa7jdFqvNkdqOtHtom03gdsNxhK7d0rD+pKS0y0htR/mfcbMlreFfQ35fzX//C+QQI6lYioc/uPVutjJ5QZKwy4Bsf6yL90jeSNpzgb/NcTx/Y0BV4="


# ----------------------------------------------------------------------------
#
# build
#
# ---------------------------------------------------------------------------- 

# Node.js version
node_js: 5

# limit clone depth to 5, to speed up build
git:
    depth: 5

# cache dependencies
cache:
    pip: true
    yarn: true
    directories:
        - node_modules

# check that we actually need to build anything, and
# install yarn before anything else
before_install:
    - |
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
          TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
      fi
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.md$)|(^(\.git|\.editor|doc|material|site|scripts|CHANGELOG|LICENSE))/' || {
          echo "Only non-source files were updated, no need to trigger a build."
	      exit
      }
    - npm install -g yarn@v0.22.0

# install dependencies
install:
    - yarn install --ignore-optional
    - pip install --user -r requirements.txt

# build
script: 
    - yarn build


# ----------------------------------------------------------------------------
#
# deployment
#
# ---------------------------------------------------------------------------- 

# deploy
#   fetch web_docs and copy contents of material/ there, then commit and push
after_success:
    - |
     git config user.email "travis@travis-ci.com"
     git config user.name  "Travis CI"
     git config --global push.default simple
     git add material/
     git stash
     git remote add -t web_docs origin2 https://${DEPLOY_KEY}@github.com/stanford-rc/sherlock.git
     git fetch origin2
     git checkout web_docs
     git checkout web_theme material/
     git add -A material/
     git commit -m "Travis deploy from $TRAVIS_BRANCH to $(git rev-parse --abbrev-ref HEAD): ${TRAVIS_COMMIT:0:7}
      
     Travis build: $TRAVIS_BUILD_NUMBER"
     git push
